title: Alex Răzvan Ispas
plugins:
  - jekyll-remote-theme
remote_theme: jekyll/minima
minima:
  skin: dark
  social_links:
    - { platform: twitter, user_url: "https://twitter.com/Razvanip" }
    - { platform: github,  user_url: "https://github.com/Razvanip13" }
    - { platform: spotify,  user_url: "https://open.spotify.com/user/31dvv62gkvurpzbsdksv65ofk4yy?si=Es22oaGjQMeQR7ghAEGHzA" }
    


#google_analytics: G-NGQWNXRS74
highlighter: rouge
kramdown:
    math_engine: katex
    syntax_highlighter: rouge
